server:
  port: 8087

spring:
  application:
    name: ticket-management-service

  datasource:
    url: jdbc:postgresql://postgres:5432/meexora_ticket
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticket-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.meexora.common.kafka,com.meexora.common.dto"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

kafka:
  topic:
    booking-confirmed: booking-confirmed
    ticket-email: ticket-email

security:
  hmac:
    secret: ${HMAC_SECRET}
