server:
  port: 8086

spring:
  application:
    name: payment-service


  datasource:
    url: jdbc:postgresql://localhost:5433/meexora_payment
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticket-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.meexora.common.kafka"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


kafka:
  topic:
    payment-status-update: payment-status-update


stripe:
  secret-key: sk_test_51RMCFxC6bH50redfcipovuHRA4umPwmWPlecPR1nU9x5Rlg4EqUnzV6w5H7B9d5YptIke91ywsUuIlvsI7rNVsco00vS7fVLxq
  public-key: pk_test_51RMCFxC6bH50redfyvGMobfeb48oESkfsNNjC48cdxAprCTl5wtCacqR6nXd0gh1sWqpDGRogGbEhnvN9m5AIp8G00ycSpsbAM
  webhook-secret: whsec_21e6d13764b23652eb2fd2b7de12ced43af58c54ed1e870ec8c79e756eee89af
