spring:
  application:
    name: event-service


  datasource:
    url: jdbc:postgresql://localhost:5433/meexora_event
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

kafka:
  topic:
    event-created: event-created
    event-edited: event-edited

client:
  booking-service:
    url: http://BOOKING-SERVICE